In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [2]:
# 케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러옵니다.
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [3]:
# 전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'

In [4]:
# 해당 텍스트를 토큰화합니다.
result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result) # 띄어쓰기 -> 형태소 단위
# 토큰? 언어모델에서 자연어 처리를 수행하는 처리 단위(단어, 문장, 문단, 글자)
# 자연어 처리 도구 : konlpy(mecab, okt, kkma, ..., 한국어 자연어 처리도구), nltk(영어), ... keras(keras.preprocessing.text)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [5]:
# ex) 언어 모델링 과정
# 1) 텍스트 수집
# 2) 텍스트 전처리 & 토큰화(nltk, konlpy, ...)
# 3) 텍스트 인코딩
# 4) 텍스트 패딩
# 5) 모델링(LSTM, BERT, GPT ...)
# 6) 모델 학습
# 7) 모델 평가

In [38]:
# 전처리하려는 세 개의 문장을 정합니다.
# docs는 corpus
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

In [39]:
# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer()             # 토큰화 함수 지정
token.fit_on_texts(docs)       # 토큰화 함수에 문장 적용

In [40]:
# 코퍼스(corpus) : 특정 도메인 낱말 낱말 집합(일반 사전 x, 전문 용어 사전 느낌)
# ex) 법률 사전(피의자, 피해자, ...), 의료 사전(코퍼스)(수술, 환자, 감염병, ...), ...

In [41]:
print("\n단어 카운트:\n", token.word_counts)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 1), ('합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [42]:
print("\n문장 카운트: ", token.document_count)


문장 카운트:  3


In [43]:
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)


각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'단어를': 1, '토큰화': 1, '텍스트의': 2, '각': 1, '합니다': 1, '먼저': 1, '나누어': 1, '단어로': 1, '딥러닝에서': 2, '토큰화해야': 1, '인식됩니다': 1, '사용할': 1, '수': 1, '있습니다': 1, '결과는': 1, '토큰화한': 1})


In [44]:
print("\n각 단어에 매겨진 인덱스 값:\n",  token.word_index)


각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화': 7, '합니다': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


In [51]:
text="오랫동안 꿈꾸는 이는 그 꿈을 닮아간다 꿈꾸는 사람은 꿈을" #코퍼스

In [52]:
token = Tokenizer()
token.fit_on_texts([text])

In [53]:
print(token.word_index)

{'꿈꾸는': 1, '꿈을': 2, '오랫동안': 3, '이는': 4, '그': 5, '닮아간다': 6, '사람은': 7}


In [54]:
sent1="나는 꿈을 꿨습니다 사람은 꿈을 꿉니다" # 테스트
# sent2 = '열이 많이 나고 기침이 나는데요. 어떻게 치료를 받아야 할까요?' # 테스트

In [55]:
token.texts_to_sequences([sent1])

[[2, 7, 2]]

In [56]:
# 코퍼스 -> 전처리 -> 언어모델(lstm기반 감정분류기)
# 테스트 : 새로운 문장 -> 언어모델(lstm기반 감정분류기) -> 인코딩([[2,7,2]])
# => 언어모델(lstm기반 감정분류기) => 긍정/부정 t\

In [57]:
token.word_index

{'꿈꾸는': 1, '꿈을': 2, '오랫동안': 3, '이는': 4, '그': 5, '닮아간다': 6, '사람은': 7}

In [60]:
text="오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

In [62]:
x = token.texts_to_sequences([text])
x

[[3, 1, 4, 5, 2, 6]]

In [63]:
#인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]]]


In [64]:
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])

In [65]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

# 영화 리뷰 코퍼스에는 토큰이 20개 존재

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [66]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [67]:
# 패딩 : 모든 문장의 길이(토큰의 개수)를 동일하게 맞춰주는 작업
padded_x = pad_sequences(x, 4)
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [68]:
# 임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) +1

In [69]:
word_size # 20개 + 0번

21

In [74]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 4, 8)              168       
                                                                 
 flatten_1 (Flatten)         (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 201 (804.00 Byte)
Trainable params: 201 (804.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [75]:
padded_x

array([[ 0,  0,  1,  2],
       [ 0,  0,  0,  3],
       [ 4,  5,  6,  7],
       [ 0,  8,  9, 10],
       [ 0, 11, 12, 13],
       [ 0,  0,  0, 14],
       [ 0,  0,  0, 15],
       [ 0,  0, 16, 17],
       [ 0,  0, 18, 19],
       [ 0,  0,  0, 20]], dtype=int32)

In [76]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 595ms/step - loss: 0.6902 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6882 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6862 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6841 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6821 - accuracy: 0.6000
Epoch 6/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6801 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6781 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6761 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6741 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6721 - accuracy: 0.7000
Epoch 11/20
1/1 [==============

In [80]:
# 참 재밌네요 최고에요
# msg = array([[0, 4, 2, 3]])

msg = array([[0,0,4,17]]) # 참 지루하네요

In [79]:
model.predict(msg) # 참 재밌네요 최고에요 -> 0.5 < msg 긍정

1/1 [==============================] - 0s 33ms/step


array([[0.5061281]], dtype=float32)

In [81]:
model.predict(msg) # 참 지루하네요 -> 0.5 > msg 부정

1/1 [==============================] - 0s 20ms/step


array([[0.46486655]], dtype=float32)