In [1]:
# python, numpy, pandas
# 통계분석
# 데이터마이닝
# 시각화(matplotlib, tableau, seaborn, plotly, ...)

# 머신러닝(scikit-learn)
# 딥러닝(tensorflow, keras, pytorch) - cnn, rnn(lstm), r1, yolo 등

In [2]:
import numpy as np
np.random.seed(12345)

In [3]:
np.set_printoptions(precision=4) # 반올림 4자리까지 변경(5자리에서 반올림)

In [4]:
# 반올림(기본값 8자리), 자릿수 지정

In [5]:
np.array([1.23456789])

array([1.2346])

In [8]:
np.set_printoptions(precision=8)

In [9]:
np.array([1.23456789])

array([1.23456789])

In [12]:
np.arange(10000) # 1000개까지는 전체 출력, 1000개 초과시 ... 으로 표현 출력

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [15]:
# 1000개 초과여도 전체 출력
# np.set_printoptions(threshold=2000)
np.set_printoptions(threshold=np.inf) # 무한대 전체 출력

In [16]:
np.arange(15000)

array([    0,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99,   100,   101,   102,   103,   104,   105,   106,   107,
         108,   109,   110,   111,   112,   113,   114,   115,   116,
         117,   118,   119,   120,   121,   122,   123,   124,   125,
         126,   127,

In [19]:
# 표준 정규 분포(평균=0, 표준편차=1)에서 무작위 샘플을 생성하고 이 샘플들을 NumPy 배열로 반환
data = [np.random.standard_normal() for i in range(7)]
data

[0.2817461528302025,
 0.7690225676118387,
 1.2464347363862822,
 1.0071893575830049,
 -1.2962211091122635,
 0.274991633432124,
 0.22891287893531592]

In [18]:
a = [1,2,3]
b = a # 동일한 메모리 주소 값, a 값이 바뀌면 b도 바뀜

In [20]:
a==b

True

In [23]:
a.append(4)
a

[1, 2, 3, 4]

In [24]:
b

[1, 2, 3, 4]

In [21]:
c = a.copy()
c

[1, 2, 3]

In [22]:
a == c

True

In [25]:
c

[1, 2, 3]

In [26]:
c = """
This is a longer string that
spans multiple lines
"""

In [27]:
c.count('\n')

3

In [28]:
a = "this is a string"

In [29]:
b = a.replace('string', 'longer string')
b

'this is a longer string'

In [30]:
a = 5.6
s = str(a)
print(s)

5.6


In [31]:
s = "12\\34"
print(s)

12\34


In [32]:
a = "this is the first half "
b = "and this is the second half"
a + b

'this is the first half and this is the second half'

In [33]:
template = "{0:.2f} {1:s} are worth US${2:d}" # 소수이하 둘째자리 s:문자열 d:10진정수

In [34]:
template.format(88.46, "Argentine Pesos", 1)

'88.46 Argentine Pesos are worth US$1'

In [35]:
amount = 10
rate = 88.46
currency = "Pesos"
result = f"{amount} {currency} is worth US${amount / rate}"

In [36]:
result

'10 Pesos is worth US$0.11304544426859599'

In [37]:
False or True

True

In [38]:
from datetime import datetime, date, time
dt = datetime(2024, 5, 21, 9, 45, 21)

In [39]:
dt

datetime.datetime(2024, 5, 21, 9, 45, 21)

In [43]:
dt.day
dt.minute
dt.date()

datetime.date(2024, 5, 21)

In [44]:
dt.time()

datetime.time(9, 45, 21)

In [45]:
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
          "south   carolina##", "West virginia?"]

In [47]:
import re

In [52]:
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub("[!#?]", "", value)
        value = value.title() # 첫번째 단어 대문자로 변경
        result.append(value)
    return result

In [53]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [55]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [56]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [57]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [58]:
float_arr.dtype

dtype('float64')

In [59]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [60]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [61]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [62]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr[5]
arr[5:8]
arr[5:8] = 12

In [66]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [67]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [68]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [69]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr2d[2]
arr2d[2][1] # arr2d[2,1]

8

In [70]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])

In [76]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [77]:
names[names == 'Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [78]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [80]:
data[names == 'Bob',1]
data[names == 'Bob', 0:]

array([[4, 7],
       [0, 0]])

In [81]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [82]:
names != 'Bob' # not equal, !=

array([False,  True,  True, False,  True,  True,  True])

In [83]:
names == 'Bob'
# !(names == 'Bob') 문법 오류
~(names == 'Bob') # ~는 부정

array([False,  True,  True, False,  True,  True,  True])

In [84]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [85]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [88]:
# names가 Bob이 아닌 사람들에 대한 data 배열의 값을 출력하시오
data[names != 'Bob']
data[~(names == 'Bob')] # names=Bob인 것에대한 부정

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [90]:
cond = (names=='Bob')
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [95]:
names
# Bob 또는 Will에 대한 data 배열 값을 추출하시오
cond = (names=='Bob') | (names=='Will') # | : or, & : and
data[cond]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [96]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [97]:
data<0 # 배열의 각각의 요소들에 대해 비교 연산

array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [98]:
data[data<0]

array([ -5, -12,  -4])

In [99]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [100]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [101]:
# names에서 이름이 Joe가 아닌 사람들에 대한 data 요소 값을 모두 7로 변경하시오
data[names != 'Joe'] = 7
data

array([[  7,   7],
       [  0,   2],
       [  7,   7],
       [  7,   7],
       [  7,   7],
       [-12,  -4],
       [  3,   4]])

In [102]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [103]:
arr[4]

array([4., 4., 4., 4.])

In [110]:
# arr[4,3] 4행 3열 값 추출
arr[[4,3,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [6., 6., 6., 6.]])

In [114]:
arr[7]
arr[-1]
arr[[-1, -5, -3]]

array([[7., 7., 7., 7.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.]])

In [115]:
arr[[-1, -5, -3], 2:]

array([[7., 7.],
       [3., 3.],
       [5., 5.]])

In [116]:
arr[[-1, -5, -3], 1:3]

array([[7., 7.],
       [3., 3.],
       [5., 5.]])

In [117]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [142]:
# 행인덱스 1,5,7,2번 행 추출, 0,3,1,2번 순서로 열 추출
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [ ]:
# arr[[1,5,7,2], 0]
# 배열명[[행번호], [열번호]] (행번호, 열번호) 쌍에 대한 요소값 추출
arr[[1,5,7,2], [0,3,1,2]] # 1번행0번열, 5번행3번열, ...

In [144]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [143]:
arr[[1,5,7,2]][:,[0,3,1,2]] # 행 추출 후 열의 순서 지정하여 추출

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [145]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [148]:
arr[:,[0,3,1,2]][[1,5,7,2]] # 열 순서 지정하여 추출 후 행 추출

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [154]:
arr[[1,5,7,2],[0,3,1,2]] = 0

In [155]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [156]:
arr[[1,5,7,2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  0,  0,  0],
       [24, 25, 26, 27],
       [ 0,  0,  0,  0]])

In [157]:
arr = np.arange(15).reshape((3, 5))
arr # 5행 3열

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [158]:
arr.T # 3행 5열

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [160]:
arr @ arr.T # 5행3열 @ 3행 5열 = 5행 5열

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [163]:
arr.T @ arr # 3행5열 @ 5행3열 = 3행 3열

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [164]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [166]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [177]:
# [1.1, 2.2, 1.3, 1.4, 2.5]
# cond가 True이면 xarr, False 이면 yarr 요소값이 출력
# res = []
# for i in range(len(cond)):
#     if cond[i] == True:
#         res.append(xarr[i])
#     else:
#         res.append(yarr[i])
# res
res = []
for i, v in enumerate(cond):
    if v:
        res.append(xarr[i])
    else:
        res.append(yarr[i])
np.array(res)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [178]:
[x if z else y for x, y, z in zip(xarr, yarr, cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [179]:
# np.where(조건, 참, 거짓)
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [186]:
arr = np.random.standard_normal((4,4))

In [187]:
# arr = np.random.standard_normal((4,4))
arr > 0

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True, False, False, False]])

In [188]:
np.where(arr>0, 1, -1)

array([[ 1,  1,  1, -1],
       [-1, -1, -1, -1],
       [-1,  1,  1,  1],
       [ 1, -1, -1, -1]])

In [190]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
# arr에서 3의 배수는 3, 아니면 원래 값을 출력(0도3의 배수라 생각)
np.where(arr%3==0, 3, arr)

array([[ 3,  1,  2,  3],
       [ 4,  5,  3,  7],
       [ 8,  3, 10, 11]])

In [192]:
np.mean(arr)

5.5

In [193]:
arr.mean(axis=1)

array([1.5, 5.5, 9.5])

In [194]:
arr.mean(axis=0)

array([4., 5., 6., 7.])

In [196]:
arr = np.array([0,1,2,3,4,5,6,7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [197]:
arr.sum()

28

In [198]:
arr = np.random.standard_normal(100)
arr

array([-0.72621349,  0.22289555,  0.0513161 , -1.15771947,  0.81670694,
        0.43360961,  1.01073695,  1.82487521, -0.99751825,  0.8505911 ,
       -0.1315776 ,  0.91241415,  0.18821068,  2.16946144, -0.1149282 ,
        2.00369736,  0.02961015,  0.79525316,  0.11810975, -0.74853155,
        0.58496974,  0.15267657, -1.56565729, -0.56254019, -0.03266414,
       -0.9290062 , -0.48257265, -0.03626385,  1.09539006,  0.98092848,
       -0.58948769,  1.58170009, -0.52873483,  0.45700187,  0.92996876,
       -1.56927061, -1.02248698, -0.40282692,  0.22048686, -0.19340111,
        0.66915834, -1.64898482, -2.25279725, -1.16683222,  0.3536071 ,
        0.70211017, -0.2745692 , -0.13914219,  0.10765722, -0.60654513,
       -0.41706441, -0.01700704, -1.22414528, -1.80083991,  1.6347362 ,
        0.9890083 ,  0.45794014,  0.55515441,  1.30671972, -0.44055357,
       -0.30135028,  0.49879149, -0.82399104,  1.32056584,  0.50796479,
       -0.65343768,  0.18697951, -0.39172525, -0.27229298, -0.01

In [200]:
(arr > 0).sum()

48

In [201]:
(arr <= 0).sum()

52

In [204]:
bools = np.array([False, False, True, False])
bools.sum()
bools.any() # 1개 이상 True이면 True
bools.all() # 모두 True이면 True

False

In [205]:
arr2 = np.array([5,-10, 7, 1, 0, -3])
arr2

array([  5, -10,   7,   1,   0,  -3])

In [206]:
np.sort(arr2)

array([-10,  -3,   0,   1,   5,   7])

In [207]:
arr2

array([  5, -10,   7,   1,   0,  -3])

In [208]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [211]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [212]:
set(names)
set(ints)

{1, 2, 3, 4}

In [213]:
arr

array([-0.72621349,  0.22289555,  0.0513161 , -1.15771947,  0.81670694,
        0.43360961,  1.01073695,  1.82487521, -0.99751825,  0.8505911 ,
       -0.1315776 ,  0.91241415,  0.18821068,  2.16946144, -0.1149282 ,
        2.00369736,  0.02961015,  0.79525316,  0.11810975, -0.74853155,
        0.58496974,  0.15267657, -1.56565729, -0.56254019, -0.03266414,
       -0.9290062 , -0.48257265, -0.03626385,  1.09539006,  0.98092848,
       -0.58948769,  1.58170009, -0.52873483,  0.45700187,  0.92996876,
       -1.56927061, -1.02248698, -0.40282692,  0.22048686, -0.19340111,
        0.66915834, -1.64898482, -2.25279725, -1.16683222,  0.3536071 ,
        0.70211017, -0.2745692 , -0.13914219,  0.10765722, -0.60654513,
       -0.41706441, -0.01700704, -1.22414528, -1.80083991,  1.6347362 ,
        0.9890083 ,  0.45794014,  0.55515441,  1.30671972, -0.44055357,
       -0.30135028,  0.49879149, -0.82399104,  1.32056584,  0.50796479,
       -0.65343768,  0.18697951, -0.39172525, -0.27229298, -0.01

In [214]:
np.save('data', arr) # arr에 저장된 데이터가 binary 형태로 data.npy에 저장됨

In [215]:
np.load('data.npy')

array([-0.72621349,  0.22289555,  0.0513161 , -1.15771947,  0.81670694,
        0.43360961,  1.01073695,  1.82487521, -0.99751825,  0.8505911 ,
       -0.1315776 ,  0.91241415,  0.18821068,  2.16946144, -0.1149282 ,
        2.00369736,  0.02961015,  0.79525316,  0.11810975, -0.74853155,
        0.58496974,  0.15267657, -1.56565729, -0.56254019, -0.03266414,
       -0.9290062 , -0.48257265, -0.03626385,  1.09539006,  0.98092848,
       -0.58948769,  1.58170009, -0.52873483,  0.45700187,  0.92996876,
       -1.56927061, -1.02248698, -0.40282692,  0.22048686, -0.19340111,
        0.66915834, -1.64898482, -2.25279725, -1.16683222,  0.3536071 ,
        0.70211017, -0.2745692 , -0.13914219,  0.10765722, -0.60654513,
       -0.41706441, -0.01700704, -1.22414528, -1.80083991,  1.6347362 ,
        0.9890083 ,  0.45794014,  0.55515441,  1.30671972, -0.44055357,
       -0.30135028,  0.49879149, -0.82399104,  1.32056584,  0.50796479,
       -0.65343768,  0.18697951, -0.39172525, -0.27229298, -0.01

In [216]:
brr = np.arange(10)
brr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [217]:
np.savez('data2.npz', a=arr, b=brr)

In [218]:
x = np.load('data2.npz')
x

In [220]:
x['a']
x['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
brr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [224]:
brr.max()
brr.min()
brr.mean()

4.5

In [225]:
# 데이터 분석 대상 자료의 유형
# 시계열(시간의 흐름에 따라 변화하는 데이터(아니여도 상관없음), series) -> Series
# 표(table)

# Pandas는 Series와 DataFrame 클래스를 제공

In [226]:
import pandas as pd

In [227]:
# python : list, set, dict, tuple
# numpy : ndim array
# pandas : Series, DataFrame
# Series : numpy 1차원 array와 매우 유사함. 차이점은 Series는 index가 있다
# 시리즈 = 데이터 + 인덱스
# DataFrame : numpy 2차원 array와 매우 유사함, 차이점은 DataFrame는 행 index, 열 index가 있음
# 데이터프레임 = 데이터(2차원) + 행 인덱스 + 열 인덱스

In [229]:
li = [1,2,3]
li
np.array(li)

array([1, 2, 3])

In [234]:
s = pd.Series([10,20,30,40]) # 행 인덱스 자동 부여(0번~)
s

0    10
1    20
2    30
3    40
dtype: int64

In [236]:
s2 = pd.Series([10,20,30,40], index=['월', '화', '수', '목']) # 행 인덱스 자동 부여(0번~)
# pd.Series(데이터, 인덱스)
s2

월    10
화    20
수    30
목    40
dtype: int64

In [237]:
s3 = pd.Series([90,70,60,80], index=['홍길동', '임꺽정', '세종', '인조']) # 몸무게
s3

홍길동    90
임꺽정    70
세종     60
인조     80
dtype: int64

In [238]:
pd.Series(list(range(10,15)))

0    10
1    11
2    12
3    13
4    14
dtype: int64

In [239]:
s3

홍길동    90
임꺽정    70
세종     60
인조     80
dtype: int64

In [240]:
s3.index

Index(['홍길동', '임꺽정', '세종', '인조'], dtype='object')

In [241]:
s3.values

array([90, 70, 60, 80], dtype=int64)

In [242]:
s3.index.name = '인물'

In [243]:
s3.name='몸무게'

In [244]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [245]:
s3/10

인물
홍길동    9.0
임꺽정    7.0
세종     6.0
인조     8.0
Name: 몸무게, dtype: float64

In [246]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [250]:
# s3['세종']
# s3[2]
s3.iloc[2]

60

In [258]:
# s3['임꺽정']
s3[['임꺽정', '세종']]
# s3[1]

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [259]:
# s3.iloc[1]
# s3[[1,2]]
s3.iloc[[1,2]]

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [260]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [261]:
s3 > 70

인물
홍길동     True
임꺽정    False
세종     False
인조      True
Name: 몸무게, dtype: bool

In [264]:
s3[s3>70]
# s3에서 데이터 값이 60이상 80 이하인 자료를 추출하시오
s3[(s3>=60) & (s3<=80)]

인물
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [265]:
s3.iloc[1:3] # 3 포함 x

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [266]:
s3['임꺽정':'인조'] # 인조 포함

인물
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [269]:
# 1. 동전을 20번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 실험을 파이썬으로 작성하여 출력해보자(numpy)
np.random.randint(0,2,20)

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [270]:
# 2. 주사위를 10000번 던져서 나오는 숫자의 평균을 구하라.(numpy)
np.mean(np.random.randint(1,7,10000))

3.5086

In [281]:
# 3. 난수로 이루어진 4 x 5 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.(numpy)
arr = np.random.rand(4,5)
arr

array([[0.70663448, 0.90943875, 0.54902641, 0.10687938, 0.3837938 ],
       [0.88678921, 0.55915458, 0.17808733, 0.30123992, 0.99835691],
       [0.55052988, 0.95006682, 0.32675166, 0.1144691 , 0.87455955],
       [0.73827509, 0.42598248, 0.48360255, 0.14929359, 0.57280624]])

In [291]:
# 전체의 최댓값
np.max(arr)
# 각 행의 합
np.sum(arr, axis=1)
# 각 행의 최댓값
np.max(arr, axis=1)
# 각 열의 평균
np.mean(arr, axis=0)
# 각 열의 최솟값
np.min(arr, axis=0)

array([0.55052988, 0.42598248, 0.17808733, 0.10687938, 0.3837938 ])

In [295]:
# 4.  다음 데이터를 시리즈 구조로 정의하고 '광주' 도시의 인구를 참조하시오
# 서울-1000, 부산-300, 인천-200, 광주-100
city = pd.Series([1000, 300, 200, 100], index=['서울', '부산', '인천', '광주'])
city['광주']

100

In [297]:
# 5. 다음의 Series를 생성하고 sample 변수에 대입하고 출력하세요
# [출력]
# 가    10
# 나    20
# 다    30
# 라    40
# 마    50
# dtype: int64
sample = pd.Series([10,20,30,40,50], index=['가', '나', '다', '라', '마'])
sample

가    10
나    20
다    30
라    40
마    50
dtype: int64

In [302]:
# 6. sample중 '나'와 '라' 데이터를 조회하세요
sample[['나', '라']]

나    20
라    40
dtype: int64

In [307]:
# *기본 코드*
np.random.seed(20)
sample2 = pd.Series(np.random.randint(100, 200, size=(15,)))
sample2
# 7. sample2 중 160 이하인 데이터만 필터하세요
sample2[sample2 <=160]
# 8. sample2 중 130 이상 170 이하인 데이터만 필터하세요
sample2[(sample2 >=130) & (sample2<=170)]

11    134
13    140
dtype: int32

In [308]:
# 9.다음과 같은 Series를 생성해 주세요
# [출력]
# 가     apple
# 나       NaN
# 다    banana
# 라      kiwi
# 마    gubong
# dtype: object
pd.Series(['apple', 'NaN', 'banana', 'kiwi', 'gubong'], index=['가', '나', '다', '라', '마'])

가     apple
나       NaN
다    banana
라      kiwi
마    gubong
dtype: object

In [312]:
# 10. 
# - 숫자로 이루어진 리스트에서 사용자가 입력한 숫자를 검색하는 모듈을 다음 요건에 따라 만들어 보자
# - 검색 모듈은 선형 검색 알고리즘을 이용하자
# - 리스트는 1부터 20까지의 정수 중에서 난수 10개를 이용한다.
# -검색에 성공하면 해당 정수의 인덱스를 출력하고, 검색 결과가 없다면 -1을 출력하자
li = np.random.randint(1,21,10)
li

array([16, 19, 15, 20, 11, 11,  2, 19, 18,  9])

In [320]:
a = int(input('찾는 수 : '))
for i in li:
    if a == i:
        print(np.where(li == a)[0][0])
        break
if a not in li:
    print(-1)

찾는 수 : 16
0


In [ ]:
li